package cn.iyunbei.handself.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.iyunbei.handself.bean.GoodsBeanDao;
import cn.iyunbei.handself.bean.OrderIdDao;
import cn.iyunbei.handself.bean.OrderBeanDao;

import cn.iyunbei.handself.greendao.GoodsBeanDaoDao;
import cn.iyunbei.handself.greendao.OrderIdDaoDao;
import cn.iyunbei.handself.greendao.OrderBeanDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsBeanDaoDaoConfig;
    private final DaoConfig orderIdDaoDaoConfig;
    private final DaoConfig orderBeanDaoDaoConfig;

    private final GoodsBeanDaoDao goodsBeanDaoDao;
    private final OrderIdDaoDao orderIdDaoDao;
    private final OrderBeanDaoDao orderBeanDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsBeanDaoDaoConfig = daoConfigMap.get(GoodsBeanDaoDao.class).clone();
        goodsBeanDaoDaoConfig.initIdentityScope(type);

        orderIdDaoDaoConfig = daoConfigMap.get(OrderIdDaoDao.class).clone();
        orderIdDaoDaoConfig.initIdentityScope(type);

        orderBeanDaoDaoConfig = daoConfigMap.get(OrderBeanDaoDao.class).clone();
        orderBeanDaoDaoConfig.initIdentityScope(type);

        goodsBeanDaoDao = new GoodsBeanDaoDao(goodsBeanDaoDaoConfig, this);
        orderIdDaoDao = new OrderIdDaoDao(orderIdDaoDaoConfig, this);
        orderBeanDaoDao = new OrderBeanDaoDao(orderBeanDaoDaoConfig, this);

        registerDao(GoodsBeanDao.class, goodsBeanDaoDao);
        registerDao(OrderIdDao.class, orderIdDaoDao);
        registerDao(OrderBeanDao.class, orderBeanDaoDao);
    }
    
    public void clear() {
        goodsBeanDaoDaoConfig.clearIdentityScope();
        orderIdDaoDaoConfig.clearIdentityScope();
        orderBeanDaoDaoConfig.clearIdentityScope();
    }

    public GoodsBeanDaoDao getGoodsBeanDaoDao() {
        return goodsBeanDaoDao;
    }

    public OrderIdDaoDao getOrderIdDaoDao() {
        return orderIdDaoDao;
    }

    public OrderBeanDaoDao getOrderBeanDaoDao() {
        return orderBeanDaoDao;
    }

}
